apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: nginx
spec:
  replicas: 1 # kpt-set: ${replicas}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: service-a
        image: nginx:1.14.2 # kpt-set: nginx:${tag}
        ports:
        - containerPort: 80
